version: '3'
services:
  reverse-proxy:
          image: traefik
          command:
              - "--api=true"
              - "--api.insecure=true"
              - "--api.dashboard=true"
              - "--providers.docker=true"
              - "--providers.docker.exposedbydefault=false"
              - "--providers.docker.endpoint=unix:///var/run/docker.sock"
              - "--entrypoints.web.address=:80"
          ports:
                # The HTTP port
                - "80:80"
          volumes:
          # So that Traefik can listen to the Docker events
          - /var/run/docker.sock:/var/run/docker.sock
          labels:
              - "traefik.enable=True"
              - "traefik.http.routers.dashboard.rule=Host(`0.0.0.0`)"
              - "treafik.http.routers.dashboard.service=api@internal"
              - "traefik.docker.network=smvsite-deployment_front"
              - "traefik.docker.network=front"
              - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
              - "traefik.port=8080"
              - "traefik.http.routers.dashboard.middlewares=traefik-auth"
              - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$8EVjn/nj$$GiLUZqcbueTFeD23SuB6x0"
          networks:
              - front
  database:
    image: postgres:alpine
    env_file:
      - .env/postgres.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "postgres" ]
            timeout: 45s
            interval: 10s
            retries: 10
    networks:
            - back
  django:
    image: smvsite/smvsite
    env_file:
      - .env/django.env
    depends_on:
            database:
                    condition:  service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`127.0.0.1`) && PathPrefix(`/`)"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
      - "traefik.docker.network=smvsite-deployment_front"
      - "traefik.port=8000"
    networks:
            - back
            - front
networks:
        back:
             driver: bridge
             ipam:
                config:
                  - subnet: 10.5.0.0/16
                    gateway: 10.5.0.1
        front:
            driver: bridge
            ipam:
               config:
                 - subnet: 10.6.0.0/16
                   gateway: 10.6.0.1
