version: '3'
services:
  database:
    image: postgres:alpine
    env_file:
      - .env/postgres.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "postgres" ]
            timeout: 45s
            interval: 10s
            retries: 10
    networks:
            - back
  django:
    image: smvsite/smvsite
    env_file:
      - .env/django.env
    depends_on:
            database:
                    condition:  service_healthy
    ports:
    - "8000:8000"
    networks:
            - back
       

networks:
        back:
             driver: bridge
             ipam:
                config:
                  - subnet: 10.5.0.0/16
                    gateway: 10.5.0.1
